version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres_medilogs
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medilogs
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/db/script.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    networks:
      - medilogs_net

networks:
  medilogs_net:

volumes:
  postgres_data:
    driver: local
